server:
  port: 8082
security:
  oauth2:
    client:
      client-id: { client-id }
      client-secret: { client-secret }
    resource:
      jwt:
        keyUri: http://localhost:8081/oauth/token_key